# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: bda3b417c56d832011c9c1f404b6d8245fcf78096805b0b45d090b907d7577f36d6bb57416cae39ab48d1fdb47e69f2bb0688fef6fc638c7dc50065cebe4b949

test:
  secret_key_base: d8ddacab52bbc556440645cabf5cd594f186588f137acc3b6844cc186687eeda62f9be91d178bdf180d87e70326f3edf665acee9e8fdb5cbaa0b9041d0bc93fa

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
